openapi: 3.0.1
info:
  title: CloneAPI
  description: API Definition of CloneAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/employees
paths:
  /:
    post:
      responses:
        default:
          description: Default response
