openapi: 3.0.1
info:
  title: Clone
  description: API Definition of Clone
  version: 1.0.0
servers:
- url: http://localhost:8290/cloneAPI
paths:
  /:
    post:
      responses:
        default:
          description: Default response
