openapi: 3.0.1
info:
  title: LogMediatorTest
  description: API Definition of LogMediatorTest
  version: 1.0.0
servers:
- url: http://localhost:8290/logtest
paths:
  /:
    get:
      responses:
        default:
          description: Default response
